name: GS.BIN
sha1: d0e17f3e271e98c4b9ac0ff26e44a529a1f67182
options:
  platform: psx
  basename: ovls
  base_path: ..
  build_path: build/
  target_path: disk/OVERLAYS/GS.BIN
  asm_path: asm/ovl/gs
  asset_path: assets/ovl/gs
  src_path: src/ovl/gs
  compiler: GCC
  symbol_addrs_path: config/symbols.ovlgs.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.ovlgs.txt
  undefined_syms_auto_path: config/undefined_syms_auto.ovlgs.txt
  ld_script_path: config/ld/ovlgs.ld
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: yes
  asm_jtbl_label_macro: jlabel
  section_order:
    - ".rodata"
    - ".text"
    - ".data"

  subalign: 2

  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

segments:
  - name: ovlgs
    type: code
    start: 0x00000000
    vram: 0x80010000
    subsegments:
      - [0x0, rodata]
  - [0x8650]