name: GG.BIN
sha1: fe4dbcaec959c190509508f17f3876640d8279f5
options:
  platform: psx
  basename: ovlgg
  base_path: ..
  build_path: build/
  target_path: disk/OVERLAYS/GG.BIN
  asm_path: asm/ovl/gg
  asset_path: assets/ovl/gg
  src_path: src/ovl/gg
  compiler: GCC
  symbol_addrs_path: config/symbols.ovlgg.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.ovlgg.txt
  undefined_syms_auto_path: config/undefined_syms_auto.ovlgg.txt
  ld_script_path: config/ld/ovlgg.ld
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: yes
  asm_jtbl_label_macro: jlabel
  section_order:
    - ".rodata"
    - ".text"
    - ".data"

  subalign: 2

  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

segments:
  - name: ovlgg
    type: code
    start: 0x00000000
    vram: 0x80010000
    subsegments:
      - [0x0, rodata]
      - [0xA4, c]
      - [0x1A48, data]
  - [0x32C0]