name: SCUS_942.27
sha1: 6e59ebb243fcb41152c29406c7f6d30629a1b8c9
options:
  basename: scus_942.27
  target_path: disk/SCUS_942.27
  base_path: ..
  platform: psx
  compiler: GCC

  asm_path: asm/main
  src_path: src/main
  build_path: build/

  find_file_boundaries: False
  ld_script_path: config/ld/main.ld

  gp_value: 0x00000000

  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path: config/symbols.main.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.main.txt
  undefined_syms_auto_path: config/undefined_syms_auto.main.txt

  extensions_path: tools/splat_ext

  subalign: 2

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: header
    type: header
    start: 0x0

  - name: main
    type: code
    start: 0x800
    vram: 0x801B0000
    bss_size: 0x0
    subsegments:
      - [0x800, c, 800]
      - [0x22C0, textbin, psyq]
      - [0x10750, rodata]
      - [0x11258, data]
  - [0x21000]
