name: SF.BIN
sha1: 3a9943f5922c2bcd8a5960bf29c738a705d15eac
options:
  platform: psx
  basename: ovlsf
  base_path: ..
  build_path: build/
  target_path: disk/OVERLAYS/SF.BIN
  asm_path: asm/ovl/sf
  asset_path: assets/ovl/sf
  src_path: src/ovl/sf
  compiler: GCC
  symbol_addrs_path: config/symbols.ovlsf.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.ovlsf.txt
  undefined_syms_auto_path: config/undefined_syms_auto.ovlsf.txt
  ld_script_path: config/ld/ovlsf.ld
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: yes
  asm_jtbl_label_macro: jlabel
  section_order:
    - ".rodata"
    - ".text"
    - ".data"

  subalign: 2

  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

segments:
  - name: ovlsf
    type: code
    start: 0x00000000
    vram: 0x80010000
    subsegments:
      - [0x0, rodata]
  - [0xCE90]