name: CREDITS.BIN
sha1: 4ac994ab3ff91dab30cb199e73320c6751965c53
options:
  platform: psx
  basename: ovlcredits
  base_path: ..
  build_path: build/
  target_path: disk/OVERLAYS/CREDITS.BIN
  asm_path: asm/ovl/credits
  asset_path: assets/ovl/credits
  src_path: src/ovl/credits
  compiler: GCC
  symbol_addrs_path: config/symbols.ovlcredits.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.ovlcredits.txt
  undefined_syms_auto_path: config/undefined_syms_auto.ovlcredits.txt
  ld_script_path: config/ld/ovlcredits.ld
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: yes
  asm_jtbl_label_macro: jlabel
  section_order:
    - ".rodata"
    - ".text"
    - ".data"

  subalign: 2

  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

segments:
  - name: ovlcredits
    type: code
    start: 0x00000000
    vram: 0x80010000
    subsegments:
      - [0x0, rodata]
      - [0xDD8, c]
      - [0x2288, data]
  - [0x33BC]