name: LANDMAP.BIN
sha1: 021af3a550f58046073a75f6d4f9d0dd462748da
options:
  platform: psx
  basename: ovllandmap
  base_path: ..
  build_path: build/
  target_path: disk/OVERLAYS/LANDMAP.BIN
  asm_path: asm/ovl/landmap
  asset_path: assets/ovl/landmap
  src_path: src/ovl/landmap
  compiler: GCC
  symbol_addrs_path: config/symbols.ovllandmap.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.ovllandmap.txt
  undefined_syms_auto_path: config/undefined_syms_auto.ovllandmap.txt
  ld_script_path: config/ld/ovllandmap.ld
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: yes
  asm_jtbl_label_macro: jlabel
  section_order:
    - ".rodata"
    - ".text"
    - ".data"

  subalign: 2

  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  disasm_unknown: True

segments:
  - name: ovllandmap
    type: code
    start: 0x00000000
    vram: 0x80010000
    subsegments:
      - [0x0, rodata]
  - [0x4F2C]