name: MEDIEVIL.EXE
sha1: 265ce5dc508002a339ae535e49a5b1b4e683b732
options:
  basename: main
  target_path: disk/medievil/MEDIEVIL.EXE
  base_path: ..
  platform: psx
  compiler: GCC

  asm_path: asm/main
  src_path: src/main
  build_path: build/
  # create_asm_dependencies: True

  #ld_script_path: medievil.exe.ld

  find_file_boundaries: False
  gp_value: 0x00000000

  o_as_suffix: True
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]
  # auto_all_sections: [".data", ".rodata", ".bss"]

  symbol_addrs_path: config/symbols.main.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.main.txt
  undefined_syms_auto_path: config/undefined_syms_auto.main.txt

  extensions_path: tools/splat_ext

  subalign: 2

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: header
    type: header
    start: 0x0

  - name: main
    type: code
    start: 0x800
    vram: 0x80021CA4
    bss_size: 0x0
    subsegments:
      - [0x800, rodata, 800]
      - [0x785B0, asm, 785B0]
  - [0xCC800]
