name: SV.BIN
sha1: 7a5b3a3f15a61ebb69e1fe98893a7fa9e3289407
options:
  platform: psx
  basename: ovlsv
  base_path: ..
  build_path: build/
  target_path: disk/OVERLAYS/SV.BIN
  asm_path: asm/ovl/sv
  asset_path: assets/ovl/sv
  src_path: src/ovl/sv
  compiler: GCC
  symbol_addrs_path: config/symbols.ovlsv.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.ovlsv.txt
  undefined_syms_auto_path: config/undefined_syms_auto.ovlsv.txt
  ld_script_path: config/ld/ovlsv.ld
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: yes
  asm_jtbl_label_macro: jlabel
  section_order:
    - ".rodata"
    - ".text"
    - ".data"

  subalign: 2

  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

segments:
  - name: ovlsv
    type: code
    start: 0x00000000
    vram: 0x80010000
    subsegments:
      - [0x0, rodata]
      - [0xD8, c]
      - [0x72D0, data]
  - [0xD214]