name: PG.BIN
sha1: ab7967451c8395c76bdc683b78d42bd60e47405d
options:
  platform: psx
  basename: ovlpg
  base_path: ..
  build_path: build/
  target_path: disk/OVERLAYS/PG.BIN
  asm_path: asm/ovl/pg
  asset_path: assets/ovl/pg
  src_path: src/ovl/pg
  compiler: GCC
  symbol_addrs_path: config/symbols.ovlpg.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.ovlpg.txt
  undefined_syms_auto_path: config/undefined_syms_auto.ovlpg.txt
  ld_script_path: config/ld/ovlpg.ld
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: yes
  asm_jtbl_label_macro: jlabel
  section_order:
    - ".rodata"
    - ".text"
    - ".data"

  subalign: 2

  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  disasm_unknown: true

segments:
  - name: ovlpg
    type: code
    start: 0x00000000
    vram: 0x80010000
    subsegments:
      - [0x0, rodata]
  - [0x94E0]
