name: LA.BIN
sha1: 03706c818baa6f1361faa9abf24607f7e8976771
options:
  platform: psx
  basename: ovlla
  base_path: ..
  build_path: build/
  target_path: disk/OVERLAYS/LA.BIN
  asm_path: asm/ovl/la
  asset_path: assets/ovl/la
  src_path: src/ovl/la
  compiler: GCC
  symbol_addrs_path: config/symbols.ovlla.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.ovlla.txt
  undefined_syms_auto_path: config/undefined_syms_auto.ovlla.txt
  ld_script_path: config/ld/ovlla.ld
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: yes
  asm_jtbl_label_macro: jlabel
  section_order:
    - ".rodata"
    - ".text"
    - ".data"

  subalign: 2

  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

segments:
  - name: ovlla
    type: code
    start: 0x00000000
    vram: 0x80010000
    subsegments:
      - [0x0, rodata]
      - [0xE8, c]
      - [0x4908, data]
  - [0x78CC]