name: MEDIEVIL.EXE
sha1: 265ce5dc508002a339ae535e49a5b1b4e683b732
options:
  basename: game
  target_path: disk/medievil/MEDIEVIL.EXE
  base_path: ..
  platform: psx
  compiler: GCC

  asm_path: asm/game
  src_path: src/game
  build_path: build/

  find_file_boundaries: True

  asm_emit_size_directive: False

  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path: config/symbols/symbols.game.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.game.txt
  undefined_syms_auto_path: config/undefined_syms_auto.game.txt
  ld_script_path: config/ld/game.ld

  extensions_path: tools/splat_ext

  subalign: 2

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: header
    type: header
    start: 0x0

  - name: game
    type: code
    start: 0x800
    vram: 0x80021CA4
    bss_size: 0x0
    subsegments:
      - [0x800, c, 800]
      - [0x88394, rodata]
      - [0x8839C, c]
      - [0x89B3C, c]
      - [0x8B3FC, c]
      - [0x91F3C, c]
      - [0x91F7C, c]
      - [0x91F8C, c]
      - [0x99AD4, rodata]
      - [0x99ADC, c]
      - [0x9B12C, c]
      - [0x9B28C, c]
      - [0x9B31C, c]
      - [0x9CA3C, c]
      - [0x9CFDC, c]
      - [0x9D05C, c]
      - [0x9D3DC, c]
      - [0x9D46C, c]
      - [0x9D4CC, c]
      - [0x9D5BC, c]
      - [0xA3E88, data]
  - [0xCC800]
